name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
    
    - name: Run tests
      run: ./gradlew test --no-daemon
    
    - name: Upload test reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          **/build/reports/tests/
          **/build/test-results/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          launcher/build/libs/*.jar
          engine/build/libs/*.jar

  build-native-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm-community'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build native image
      run: ./gradlew :launcher:nativeCompile --no-daemon
      continue-on-error: true
    
    - name: Upload native image
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: native-image-linux
        path: launcher/build/native/nativeCompile/

  # Windows native image build (requires Windows runner)
  # Uncomment if Windows runners are available
  # build-native-image-windows:
  #   runs-on: windows-latest
  #   needs: build-and-test
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   
  #   - name: Set up GraalVM
  #     uses: graalvm/setup-graalvm@v1
  #     with:
  #       java-version: '17'
  #       distribution: 'graalvm-community'
  #       components: 'native-image'
  #       github-token: ${{ secrets.GITHUB_TOKEN }}
  #   
  #   - name: Build native image
  #     run: .\gradlew.bat :launcher:nativeCompile --no-daemon
  #   
  #   - name: Upload native image
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: PoorCraftRefactor-windows
  #       path: launcher/build/native/nativeCompile/PoorCraftRefactor.exe
